# Generated by Django 5.2.5 on 2026-02-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenhealth', '0002_topic_entry_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
