# Generated by Django 5.2.5 on 2026-02-28 10:51

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenhealth', '0003_alter_entry_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='topic',
        ),
        migrations.AlterField(
            model_name='revision',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='womenhealth.entry'),
        ),
        migrations.CreateModel(
            name='FoodComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='food_components',
            field=models.ManyToManyField(blank=True, related_name='entries', to='womenhealth.foodcomponent'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='womenhealth.entry')),
                ('foodcomponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='womenhealth.foodcomponent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='foodcomponent',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_foodcomponent'),
        ),
    ]
