# Generated by Django 5.2.5 on 2026-03-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('womenhealth', '0004_remove_revision_topic_alter_revision_entry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='foodcomponent',
            new_name='food_component',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='entry',
        ),
    ]
